[package]
name = "ktls"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.133"
thiserror = "1.0.37"
tracing = "0.1.36"
tokio-rustls = "0.23.4"
rustls = "0.20.6"
memoffset = "0.6.5"
pin-project-lite = "0.2.9"
tokio = "1.21.2"

[dependencies.ktls-sys]
# path = "../ktls-sys"
git = "https://github.com/hapsoc/ktls-sys"
rev = "798466d"

[patch.crates-io]
rustls = { git = "https://github.com/hapsoc/rustls", rev = "27617873" }

[dev-dependencies]
rcgen = "0.9.4"
tokio = { version = "1.21.2", features = ["full"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
